### ISSUE TITLE
Dependencies conflict

### ISSUE THREAD

**Issue by myiqtestercoma** [michaelshimeles/nextjs-starter-kit#7]
I get this when npm install: Does anyone get
yassinebelatar@192 nextjs14-starter-template % sudo npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nextjs-starter@0.1.0
npm ERR! Found: @tanstack/react-query@5.50.1
npm ERR! node_modules/@tanstack/react-query
npm ERR!   @tanstack/react-query@"^5.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @tanstack/react-query@"^4.18.0" from @trpc/next@10.45.2
npm ERR! node_modules/@trpc/next
npm ERR!   @trpc/next@"^10.44.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/yassinebelatar/.npm/_logs/2024-08-22T15_52_10_870Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/yassinebelatar/.npm/_logs/2024-08-22T15_52_10_870Z-debug-0.log
yassinebelatar@192 nextjs14-starter-template % clear
this is the nextjs starter kit https://github.com/michaelshimeles/nextjs-starter-kit

**Comment by michaelshimeles** [comment]
this is fixed, you can use npm, yarn or bun... i prefer yarn
